#!/usr/bin/env python3
"""Port-specific params.h generator for Force DX7 (not tools/gen_vst.py: this
port has no chain_params-driven Schwung DSP to link -- see build.sh). Reads
params.json (the ordered VST-parameter table derived from addon/shadow_page.conf,
see ../gen_dx7_port.py in the session that produced it) and emits build/params.h
with the same param_t shape gen_vst.py uses, so dx7_vst.c's PARAMS[]/NPARAMS
loop looks exactly like a normal port's wrapper.
    gen_params.py params.json build/params.h
"""
import json
import sys


def c_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    params = json.load(open(sys.argv[1]))
    out = sys.argv[2]
    lines = ["/* generated by gen_params.py from params.json: do not edit */",
             "#pragma once",
             "typedef struct { const char *key, *name; float min, max, def; int nopts; "
             "const char *const *opts; int string_display; } param_t;"]
    rows = []
    for i, p in enumerate(params):
        opts = p.get("options")
        if opts:
            lines.append("static const char *const OPTS_%d[] = {%s};" % (i, ", ".join(c_str(o) for o in opts)))
            d = p.get("default", opts[0] if opts else "")
            idx = opts.index(d) if d in opts else 0
            norm = idx / (len(opts) - 1) if len(opts) > 1 else 0.0
            rows.append("    {%s, %s, 0, 0, %sf, %d, OPTS_%d, 0}," % (
                c_str(p["key"]), c_str(p.get("name", p["key"])), repr(float(norm)), len(opts), i))
        elif p.get("string"):
            rows.append("    {%s, %s, 0, 0, 0, 0, 0, 1}," % (c_str(p["key"]), c_str(p.get("name", p["key"]))))
        else:
            lo, hi, d = p.get("min", 0.0), p.get("max", 1.0), p.get("default", p.get("min", 0.0))
            rows.append("    {%s, %s, %sf, %sf, %sf, 0, 0, 0}," % (
                c_str(p["key"]), c_str(p.get("name", p["key"])), repr(float(lo)), repr(float(hi)), repr(float(d))))
    lines += ["static const param_t PARAMS[] = {"] + rows + ["};", "#define NPARAMS %d" % len(params)]
    open(out, "w").write("\n".join(lines) + "\n")
    print("params.h: %d params" % len(params))


if __name__ == "__main__":
    main()
