#!/usr/bin/env python3
"""Generate the VST2 wrapper's params.h and the MPC native skin from module.json.

    vst/build/params.h                                  parameter table for vst2_wrap.c
    vst/build/skin/<VENDOR> - VST - <NAME>/             copy to /sdcard/Synths/ on the Force
        version.xml
        Plugin Skins/TUI.json                           one page per TABS entry, 8 knobs each
        Plugin Skins/Q-Links.json                       Q-Link 1..8 -> the page's knobs
        Plugin Skins/Q-Links - 8by1.json

The VST parameter index of each key is its position in module.json's
chain_params; skins bind knobs to it as "Parameter N".
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
NAME, VENDOR, UID, VERSION = "Maze Voice", "sd88me", "MzVc", 1000
AKAI = "/usr/share/Akai/Content/Synths/"

# Pages shown on the Force screen (and banked onto Q-Links 1..8), 8 keys max.
TABS = [
    ("Osc", ["vco_tune", "mod_freq", "fm_depth", "fm_eg1", "vco_eg1", "mod_eg1", "vco_key", "mod_key"]),
    ("Mixer", ["vco_lvl", "mod_lvl", "noise_lvl", "noise_tone", "ring_lvl", "sat", "level", "out_mode"]),
    ("Fold", ["fold_drive", "fold_bias", "fold_eg1", "fold_key", "blend", "route", "filt_drive", "filter_mode"]),
    ("Filter/Env", ["cutoff", "reso", "cutoff_eg1", "cutoff_key", "env1_decay", "env2_decay"]),
    ("LFO1", ["lfo1_shape", "lfo1_rate", "lfo1_sync", "lfo1_div", "lfo1_retrig", "lfo1_vco_pitch", "lfo1_mod_pitch", "lfo1_fm_depth"]),
    ("LFO1 Dest", ["lfo1_cutoff", "lfo1_env1_decay", "lfo1_env2_decay", "lfo1_filt_drive", "lfo1_fold_amt", "lfo1_fold_bias"]),
    ("LFO2", ["lfo2_shape", "lfo2_rate", "lfo2_sync", "lfo2_div", "lfo2_retrig", "lfo2_vco_pitch", "lfo2_mod_pitch", "lfo2_fm_depth"]),
    ("LFO2 Dest", ["lfo2_cutoff", "lfo2_env1_decay", "lfo2_env2_decay", "lfo2_filt_drive", "lfo2_fold_amt", "lfo2_fold_bias"]),
    ("Random", ["rnd_voice", "rnd_wavefolder", "rnd_filter", "rnd_tone", "rnd_go"]),
]


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fl(x):
    return repr(float(x)) + "f"


def gen_params(params, out):
    lines = [
        "/* generated by gen_vst.py from module.json — do not edit */",
        "#pragma once",
        "typedef struct { const char *key, *name, *unit; float min, max, def; int nopts; const char *const *opts; } param_t;",
    ]
    rows = []
    for i, p in enumerate(params):
        opts = p.get("options") or []
        if opts:
            lines.append("static const char *const OPTS_%d[] = {%s};" % (i, ", ".join(c_str(o) for o in opts)))
            d = p.get("default", 0)
            norm = (d / (len(opts) - 1)) if len(opts) > 1 else 0
            rows.append("    {%s, %s, \"\", 0, 0, %s, %d, OPTS_%d}," % (c_str(p["key"]), c_str(p["name"]), fl(norm), len(opts), i))
        else:
            lo, hi, d = p["min"], p["max"], p.get("default", p["min"])
            norm = (d - lo) / (hi - lo) if hi > lo else 0
            rows.append("    {%s, %s, %s, %s, %s, %s, 0, 0}," % (
                c_str(p["key"]), c_str(p["name"]), c_str(p.get("unit", "")), fl(lo), fl(hi), fl(norm)))
    lines.append("static const param_t PARAMS[] = {")
    lines += rows
    lines.append("};")
    lines.append("#define NPARAMS %d" % len(params))
    lines.append("#define PLUG_NAME %s" % c_str(NAME))
    lines.append("#define PLUG_VENDOR %s" % c_str(VENDOR))
    lines.append("#define PLUG_UID 0x%08x /* '%s' */" % (int.from_bytes(UID.encode(), "big"), UID))
    lines.append("#define PLUG_VERSION %d" % VERSION)
    lines.append("#define HAS_LFO_BPM 1")
    open(out, "w").write("\n".join(lines) + "\n")


def bounds(x, y, w, h, focus="Yes", show="Hide"):
    return {"version": 2, "acceptsHWFocus": focus, "showWhenDataModelInvalid": show, "whenVisible": "Always",
            "boundsType": "Absolute", "bounds": "%d %d %d %d" % (x, y, w, h), "additionalInvalidatingHandles": []}


def knob(name, index, x, y):
    return {"version": 2,
            "componentData": {"version": 1, "name": name, "type": "knobYellow", "data": {"version": 1, "handleName": "Data"}},
            "handle remapping": {"version": 1, "map": [{"key": "Data", "value": "Parameter %d" % index}]},
            "bounds": bounds(x, y, 128, 140)}


# 4 x 2 grid in the 1280 x 628 plugin area; order matches Q-Links 1..8.
def slot_xy(slot):
    return 180 + (slot % 4) * 250, 70 + (slot // 4) * 260


def gen_skin(params, outdir):
    index = {p["key"]: i for i, p in enumerate(params)}
    bg = {"version": 1, "colour": "ff1e1d1e", "image": AKAI + "AKAI Components/fx_bg.jpg"}
    comps, tabs, qmap = [], [], []
    for t, (title, keys) in enumerate(TABS):
        kids = []
        for s, k in enumerate(keys):
            x, y = slot_xy(s)
            kids.append(knob(params[index[k]]["name"], index[k], x, y))
        comps.append({"key": title, "value": {
            "version": 4, "actions": [],
            "backgroundData": {"version": 1, "focussed": bg, "unfocussed": bg},
            "ignoreMousePresses": False, "disableCoarseDataWheel": False, "repeats": 1,
            "hideQLinkBounds": False, "componentsData": kids}})
        tabs.append({"version": 3, "tabName": title, "fnKeyIndex": t, "fnKeySubIndex": 0,
                     "qlinkBoundsData": ["160 50 980 540"], "componentName": title,
                     "initialSize": "0 0 1280 628", "scale": 1.0})
        ql = {"Q-Link %d" % (q + 1): -1 for q in range(16)}
        for s, k in enumerate(keys):
            ql["Q-Link %d" % (s + 1)] = index[k]
        qmap.append({"Tab": t + 1, "SubTab": 1, "Bank Direction": "Column", "Q-Links": ql})

    tui = {"pageData": {
        "version": 1,
        "componentDefinitions": {"version": 2, "importFiles": [
            AKAI + "Generic/Generic Knob Overlay.json",
            AKAI + "Generic/Generic Menu Overlay.json",
            AKAI + "AKAI Components/AKAI Generic Components.json"],
            "localComponentDefinitions": comps},
        "info": {"version": 1, "type": "CompleteDescription"},
        "tabs": tabs}}
    qlinks = {"version": 4, "info": {"version": 1, "type": "CompleteDescription"},
              "Screen Mode Q-Links": {"version": 4, "map": qmap},
              "Program Mode Q-Links": dict(qmap[0]["Q-Links"])}

    d = os.path.join(outdir, "%s - VST - %s" % (VENDOR, NAME))
    os.makedirs(os.path.join(d, "Plugin Skins"), exist_ok=True)
    open(os.path.join(d, "version.xml"), "w").write(
        "<?xml version='1.0' encoding='utf-8'?>\n<plugincontent version=\"1.0\">\n"
        "\t<identifier>%s.vst.%s</identifier>\n\t<version>1.0.0.0</version>\n</plugincontent>\n"
        % (VENDOR, NAME.lower().replace(" ", "")))
    for f, obj in (("TUI.json", tui), ("Q-Links.json", qlinks), ("Q-Links - 8by1.json", qlinks)):
        json.dump(obj, open(os.path.join(d, "Plugin Skins", f), "w"), indent=4)
    return d


def main():
    module = json.load(open(os.path.join(ROOT, "..", "module.json")))
    caps = module.get("capabilities", module)
    params = caps.get("chain_params") or module["chain_params"]
    keys = {p["key"] for p in params}
    missing = [k for _, ks in TABS for k in ks if k not in keys]
    if missing:
        sys.exit("TABS keys not in module.json: %s" % missing)
    build = os.path.join(ROOT, "build")
    os.makedirs(build, exist_ok=True)
    gen_params(params, os.path.join(build, "params.h"))
    print("params.h: %d params" % len(params))
    print("skin:", gen_skin(params, os.path.join(build, "skin")))
    plist = ('<PLUGIN name="{n}" descriptiveName="{n}" format="VST" category="Synth" manufacturer="{v}" '
             'version="1.0" file="/sdcard/vst/maze_voice.so" uid="{u:x}" isInstrument="1" fileTime="0" '
             'infoUpdateTime="0" numInputs="0" numOutputs="2" isShell="0"/>').format(
        n=NAME, v=VENDOR, u=int.from_bytes(UID.encode(), "big"))
    open(os.path.join(build, "pluginlist-entry.xml"), "w").write(plist + "\n")


if __name__ == "__main__":
    main()
