#!/usr/bin/env python3
"""Generate the VST2 wrapper's params.h and the MPC native skin from module.json.

    vst/build/params.h                                  parameter table for vst2_wrap.c
    vst/build/skin/<VENDOR> - VST - <NAME>/             copy to /sdcard/Synths/ on the device
        version.xml
        Plugin Skins/TUI.json                           one page per TABS entry, 8 knobs each
        Plugin Skins/Q-Links.json                       Q-Link 1..8 -> the page's knobs
        Plugin Skins/Q-Links - 8by1.json

The VST parameter index of each key is its position in module.json's
chain_params; skins bind knobs to it as "Parameter N".
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
NAME, VENDOR, UID, VERSION = "Maze Voice", "sd88me", "MzVc", 1000
AKAI = "/usr/share/Akai/Content/Synths/"
FONT = os.environ.get("SKIN_FONT", "/fonts/DejaVuSans-Bold.ttf")

# Tabs -> pages -> up to 16 params. Each page is 2 rows of 8: the top row is Q-Link
# bank 1 (Q-Links 1-8), the bottom row bank 2 (9-16), matching the Force's knob row.
# Several pages in one tab become MPC sub-pages (fnKeySubIndex).
LFO_DEST = ["vco_pitch", "mod_pitch", "fm_depth", "cutoff", "env1_decay", "env2_decay", "filt_drive", "fold_amt", "fold_bias"]


def lfo_page(n):
    top = ["lfo%d_%s" % (n, k) for k in ("shape", "rate", "sync", "div", "retrig")]
    return ("LFO%d" % n, top + ["lfo%d_%s" % (n, k) for k in LFO_DEST[:3]] + ["lfo%d_%s" % (n, k) for k in LFO_DEST[3:]])


TABS = [
    ("Voice", [("Osc / Mixer", ["vco_tune", "mod_freq", "fm_depth", "fm_eg1", "vco_eg1", "mod_eg1", "vco_key", "mod_key",
                                "vco_lvl", "mod_lvl", "noise_lvl", "noise_tone", "ring_lvl", "sat", "level", "out_mode"])]),
    ("Fold / Filter", [("Fold / Filter", ["fold_drive", "fold_bias", "fold_eg1", "fold_key", "blend", "route", "filt_drive", "filter_mode",
                                          "cutoff", "reso", "cutoff_eg1", "cutoff_key", "env1_decay", "env2_decay"])]),
    ("LFO", [lfo_page(1), lfo_page(2)]),
    ("Random", [("Random", ["rnd_voice", "rnd_wavefolder", "rnd_filter", "rnd_tone", "rnd_go"])]),
]


def display_name(name):
    """Short on-screen / automation names ("LFO1 > Env1 Decay" -> "L1 Env1 Decay")."""
    for n in ("1", "2"):
        name = name.replace("LFO%s > " % n, "L%s " % n)
    return name


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fl(x):
    return repr(float(x)) + "f"


def gen_params(params, out):
    lines = [
        "/* generated by gen_vst.py from module.json — do not edit */",
        "#pragma once",
        "typedef struct { const char *key, *name, *unit; float min, max, def; int nopts; const char *const *opts; int momentary; } param_t;",
    ]
    rows = []
    for i, p in enumerate(params):
        opts = p.get("options") or []
        if opts:
            lines.append("static const char *const OPTS_%d[] = {%s};" % (i, ", ".join(c_str(o) for o in opts)))
            d = p.get("default", 0)
            norm = (d / (len(opts) - 1)) if len(opts) > 1 else 0
            rows.append("    {%s, %s, \"\", 0, 0, %s, %d, OPTS_%d, %d}," % (c_str(p["key"]), c_str(display_name(p["name"])), fl(norm), len(opts), i,
                                                                    p.get("access") == "write"))
        else:
            lo, hi, d = p["min"], p["max"], p.get("default", p["min"])
            norm = (d - lo) / (hi - lo) if hi > lo else 0
            rows.append("    {%s, %s, %s, %s, %s, %s, 0, 0, 0}," % (
                c_str(p["key"]), c_str(display_name(p["name"])), c_str(p.get("unit", "")), fl(lo), fl(hi), fl(norm)))
    lines.append("static const param_t PARAMS[] = {")
    lines += rows
    lines.append("};")
    lines.append("#define NPARAMS %d" % len(params))
    lines.append("#define PLUG_NAME %s" % c_str(NAME))
    lines.append("#define PLUG_VENDOR %s" % c_str(VENDOR))
    lines.append("#define PLUG_UID 0x%08x /* '%s' */" % (int.from_bytes(UID.encode(), "big"), UID))
    lines.append("#define PLUG_VERSION %d" % VERSION)
    lines.append("#define HAS_LFO_BPM 1")
    open(out, "w").write("\n".join(lines) + "\n")


def bounds(x, y, w, h, focus="Yes", show="Hide", kind="Absolute", visible="Always"):
    return {"version": 2, "acceptsHWFocus": focus, "showWhenDataModelInvalid": show, "whenVisible": visible,
            "boundsType": kind, "bounds": "%s %s %s %s" % (x, y, w, h), "additionalInvalidatingHandles": []}


def sub(ctype, data, bnd, name=""):
    """A child component inside a local component definition (no remapping)."""
    return {"version": 2, "componentData": {"version": 1, "name": name, "type": ctype, "data": data},
            "handle remapping": {"version": 1, "map": []}, "bounds": bnd}


def text(height, colour, just="horizontallyCentred verticallyCentred", style="SemiBold", case="Original"):
    return {"version": 1, "font": {"version": 1, "name": "Titillium Web", "style": style, "height": height},
            "colour": colour, "justification": just, "case": case}


def action(on, handler, extra=""):
    return {"version": 2, "onAction": on, "handler": handler, "handleName": "" if handler == "Show Overlay" else "Data",
            "additionalData": extra, "handle remapping": {"version": 1, "map": []}}


def focus(w, h):
    return sub("Focus", {"version": 1, "backgroundColour": "19ffffff", "outlineColour": "ffe8b41f",
                         "backgroundInset": 4.0, "outlineThickness": 2.0},
               bounds(0, 0, w, h, focus="No", show="Show", visible="WhenFocussed"), "Focus")


def local(key, actions, children):
    return {"key": key, "value": {
        "version": 4, "actions": actions,
        "backgroundData": {"version": 1, "focussed": {"version": 1, "colour": "0", "image": ""},
                           "unfocussed": {"version": 1, "colour": "0", "image": ""}},
        "ignoreMousePresses": False, "disableCoarseDataWheel": False, "repeats": 1,
        "hideQLinkBounds": False, "componentsData": children}}


CELL_W, CELL_H = 152, 284   # one control cell: name on top, control below


# Reusable control types, local to our skin (stock skins also define these locally).
def control_defs():
    name = sub("Label", {"version": 1, "textStyle": text(23, "ffc8c8c8"), "type": "Name",
                         "handleName": "Data"}, bounds(0, 2, CELL_W, 36, focus="No", show="Show"), "Name")
    value = lambda y, h, size: sub("Label", {"version": 1, "textStyle": text(size, "ffffffff"), "type": "Value",
                                             "handleName": "Data"}, bounds(0, y, CELL_W, h, focus="No", show="Show"), "Value")
    knob = sub("Knob", {"version": 5, "knobType": "FilmStrip", "filmStrip": AKAI + "AKAI Components/knob_yellow.png",
                        "numFrames": 127, "invert": False, "dragOrientation": "Vertical", "handleName": "Data"},
               bounds(26, 70, 100, 100, focus="No", show="Show"), "Knob")
    button = sub("Button", {"version": 2, "onImage": "mz_btn_on.png", "offImage": "mz_btn_off.png", "buttonId": 1,
                            "numButtonsInGroup": 1, "handleName": "Data", "gestureBehaviour": "Instant"},
                 bounds(16, 80, 120, 64, focus="No", show="Show"), "Button")
    menu_box = sub("Image", {"version": 2, "imageType": "Regular", "colour": "0", "image": "mz_menu.png"},
                   bounds(10, 60, 180, 70, focus="No", show="Show"), "Box")
    qlink = action("Mouse Down", "Q-Link")
    return [
        local("mzKnob", [qlink, action("Double Click", "Show Overlay", "knob overlay"),
                         action("Enter Pressed", "Show Overlay", "knob overlay")],
              [focus(CELL_W, CELL_H), name, knob, value(178, 40, 32)]),
        local("mzMenu", [qlink, action("Double Click", "Show Overlay", "menu overlay"),
                         action("Enter Pressed", "Show Overlay", "menu overlay")],
              [focus(CELL_W, CELL_H), name, menu_box, value(60, 70, 30)]),
        local("mzButton", [qlink, action("Enter Pressed", "Toggle Switch")],
              [focus(CELL_W, CELL_H), name, button, value(158, 40, 30)]),
        local("mzName", [], [name]),
    ]


def control_type(p):
    opts = [o.lower() for o in p.get("options") or []]
    if not opts:
        return "mzKnob"
    if len(opts) == 2 and opts[0] in ("off", "free"):
        return "mzButton"
    return "select"   # one image button per option (MPC can't list VST2 enum values in a menu)


def slug(t):
    return "".join(c if c.isalnum() else "_" for c in t).strip("_") or "x"


def select_components(p, index, x, y, defs, images):
    """Name label + a radio group of buttons (buttonId i of N) bound to the same parameter."""
    opts = p["options"]
    n = len(opts)
    cols = 1 if n <= 5 else 2
    rows = (n + cols - 1) // cols
    area_y, area_h = 44, CELL_H - 48
    bh = min(52, area_h // rows - 6)
    bw = (CELL_W - 8) // cols - 4
    out = [{"version": 2,
            "componentData": {"version": 1, "name": display_name(p["name"]), "type": "mzName", "data": {"version": 1, "handleName": "Data"}},
            "handle remapping": {"version": 1, "map": [{"key": "Data", "value": "Parameter %d" % index}]},
            "bounds": bounds(x, y, CELL_W, 36, focus="No", show="Show")}]
    for i, o in enumerate(opts):
        img = "mz_opt_%s_%dx%d" % (slug(o), bw, bh)
        images[img] = (o, bw, bh)
        key = "mzSel_%s_%d_%d" % (img[7:], i, n)
        if key not in defs:
            defs[key] = local(key, [action("Mouse Down", "Q-Link")], [
                sub("Button", {"version": 2, "onImage": img + "_on.png", "offImage": img + "_off.png", "buttonId": i,
                               "numButtonsInGroup": n, "handleName": "Data", "gestureBehaviour": "Instant"},
                    bounds(0, 0, bw, bh, focus="No", show="Show"), "Button")])
        c, r = (i % cols, i // cols)
        out.append({"version": 2,
                    "componentData": {"version": 1, "name": "%s %s" % (p["name"], o), "type": key,
                                      "data": {"version": 1, "handleName": "Data"}},
                    "handle remapping": {"version": 1, "map": [{"key": "Data", "value": "Parameter %d" % index}]},
                    "bounds": bounds(x + 4 + c * (bw + 4), y + area_y + r * (bh + 6), bw, bh,
                                     focus="Yes" if i == 0 else "No")})
    return out


def control(p, index, x, y):
    return {"version": 2,
            "componentData": {"version": 1, "name": display_name(p["name"]), "type": control_type(p),
                              "data": {"version": 1, "handleName": "Data"}},
            "handle remapping": {"version": 1, "map": [{"key": "Data", "value": "Parameter %d" % index}]},
            "bounds": bounds(x, y, CELL_W, CELL_H)}


# MPC's 4x4 Q-Link grid is numbered from the bottom row up, and with "Bank Direction:
# Column" the Force's 8 knobs walk it column by column from the top: bank 1 is
# Q-Links 13,9,5,1,14,10,6,2 and bank 2 is the same +2. Map slot s (0..15) so knob k
# of bank b controls slot b*8+k.
KNOB_QLINKS = [13, 9, 5, 1, 14, 10, 6, 2]


def qlink_for_slot(slot):
    return KNOB_QLINKS[slot % 8] + 2 * (slot // 8)


# 8 x 2 grid in the 1280 x 628 plugin area: row = Q-Link bank.
def slot_xy(slot):
    return 8 + (slot % 8) * 158, 24 + (slot // 8) * 300


def gen_images(d, images):
    """Our own button/menu artwork (never ship Akai's)."""
    from PIL import Image, ImageDraw
    def rr(path, size, fill, outline, glow=None):
        im = Image.new("RGBA", size, (0, 0, 0, 0))
        dr = ImageDraw.Draw(im)
        if glow:
            dr.rounded_rectangle([0, 0, size[0] - 1, size[1] - 1], 14, fill=glow)
        dr.rounded_rectangle([4, 4, size[0] - 5, size[1] - 5], 10, fill=fill, outline=outline, width=3)
        im.save(path)
    rr(os.path.join(d, "mz_btn_off.png"), (120, 64), (48, 48, 52, 255), (110, 110, 116, 255))
    rr(os.path.join(d, "mz_btn_on.png"), (120, 64), (232, 180, 31, 255), (255, 226, 120, 255), glow=(232, 180, 31, 90))
    rr(os.path.join(d, "mz_menu.png"), (180, 70), (36, 36, 40, 255), (232, 180, 31, 255))
    from PIL import ImageFont
    for img, (label, w, h) in images.items():
        for state, fill, outline, ink in (("off", (40, 40, 44, 255), (90, 90, 96, 255), (200, 200, 200, 255)),
                                          ("on", (232, 180, 31, 255), (255, 226, 120, 255), (20, 20, 20, 255))):
            im = Image.new("RGBA", (w, h), (0, 0, 0, 0))
            dr = ImageDraw.Draw(im)
            dr.rounded_rectangle([1, 1, w - 2, h - 2], 8, fill=fill, outline=outline, width=2)
            size = min(30, h - 12)
            while True:
                font = ImageFont.truetype(FONT, size)
                tw = dr.textlength(label, font=font)
                if tw <= w - 10 or size <= 10:
                    break
                size -= 1
            dr.text((w / 2, h / 2), label, font=font, fill=ink, anchor="mm")
            im.save(os.path.join(d, "%s_%s.png" % (img, state)))


def gen_skin(params, outdir):
    index = {p["key"]: i for i, p in enumerate(params)}
    bg = {"version": 1, "colour": "ff161618", "image": ""}
    comps, tabs, qmap = control_defs(), [], []
    sel_defs, images = {}, {}
    for t, (tab, pages) in enumerate(TABS):
        for sp, (title, keys) in enumerate(pages):
            assert len(keys) <= 16, title
            kids = []
            for s, k in enumerate(keys):
                x, y = slot_xy(s)
                p = params[index[k]]
                if control_type(p) == "select":
                    kids += select_components(p, index[k], x, y, sel_defs, images)
                else:
                    kids.append(control(p, index[k], x, y))
            comps.append({"key": title, "value": {
                "version": 4, "actions": [],
                "backgroundData": {"version": 1, "focussed": bg, "unfocussed": bg},
                "ignoreMousePresses": False, "disableCoarseDataWheel": False, "repeats": 1,
                "hideQLinkBounds": False, "componentsData": kids}})
            tabs.append({"version": 3, "tabName": title, "fnKeyIndex": t, "fnKeySubIndex": sp,
                         "qlinkBoundsData": ["0 16 1280 600"], "componentName": title,
                         "initialSize": "0 0 1280 628", "scale": 1.0})
            ql = {"Q-Link %d" % (q + 1): -1 for q in range(16)}
            for s, k in enumerate(keys):
                ql["Q-Link %d" % qlink_for_slot(s)] = index[k]
            qmap.append({"Tab": t + 1, "SubTab": sp + 1, "Bank Direction": "Column", "Q-Links": ql})

    tui = {"pageData": {
        "version": 1,
        "componentDefinitions": {"version": 2, "importFiles": [
            AKAI + "Generic/Generic Knob Overlay.json",
            AKAI + "Generic/Generic Menu Overlay.json"],
            "localComponentDefinitions": comps},
        "info": {"version": 1, "type": "CompleteDescription"},
        "tabs": tabs}}
    comps[len(control_defs()):len(control_defs())] = list(sel_defs.values())
    qlinks = {"version": 4, "info": {"version": 1, "type": "CompleteDescription"},
              "Screen Mode Q-Links": {"version": 4, "map": qmap},
              "Program Mode Q-Links": dict(qmap[0]["Q-Links"])}

    d = os.path.join(outdir, "%s - VST - %s" % (VENDOR, NAME))
    os.makedirs(os.path.join(d, "Plugin Skins"), exist_ok=True)
    open(os.path.join(d, "version.xml"), "w").write(
        "<?xml version='1.0' encoding='utf-8'?>\n<plugincontent version=\"1.0\">\n"
        "\t<identifier>%s.vst.%s</identifier>\n\t<version>1.0.0.0</version>\n</plugincontent>\n"
        % (VENDOR, NAME.lower().replace(" ", "")))
    for f, obj in (("TUI.json", tui), ("Q-Links.json", qlinks), ("Q-Links - 8by1.json", qlinks)):
        json.dump(obj, open(os.path.join(d, "Plugin Skins", f), "w"), indent=4)
    gen_images(os.path.join(d, "Plugin Skins"), images)
    return d


def main():
    module = json.load(open(os.path.join(ROOT, "..", "module.json")))
    caps = module.get("capabilities", module)
    params = caps.get("chain_params") or module["chain_params"]
    keys = {p["key"] for p in params}
    missing = [k for _, pages in TABS for _, ks in pages for k in ks if k not in keys]
    if missing:
        sys.exit("TABS keys not in module.json: %s" % missing)
    build = os.path.join(ROOT, "build")
    os.makedirs(build, exist_ok=True)
    gen_params(params, os.path.join(build, "params.h"))
    print("params.h: %d params" % len(params))
    print("skin:", gen_skin(params, os.path.join(build, "skin")))
    plist = ('<PLUGIN name="{n}" descriptiveName="{n}" format="VST" category="Synth" manufacturer="{v}" '
             'version="1.0" file="/sdcard/vst/maze_voice.so" uid="{u:x}" isInstrument="1" fileTime="0" '
             'infoUpdateTime="0" numInputs="0" numOutputs="2" isShell="0"/>').format(
        n=NAME, v=VENDOR, u=int.from_bytes(UID.encode(), "big"))
    open(os.path.join(build, "pluginlist-entry.xml"), "w").write(plist + "\n")


if __name__ == "__main__":
    main()
