#!/usr/bin/env python3
"""Generate everything a Schwung-module port needs from one small vst.json (used by tools/build_port.sh).

    gen_vst.py <port>/vst.json            -> <port>/build/params.h, skin/<vendor> - VST - <name>/, pluginlist-entry.xml
    gen_vst.py <port>/vst.json --shell    print the build settings as shell variables (for build_port.sh)

vst.json (paths are relative to the vst.json's folder):
    {
      "name": "Maze Voice", "vendor": "sd88me", "uid": "MzVc", "version": 1000,
      "so": "maze_voice.so",                     # installed as /sdcard/vst/<so>
      "module": "../module.json",                # Schwung module.json (chain_params = VST parameters, in order)
      "layout": "layout.conf",                   # optional; without it the skin studio's auto-layout is used
      "short_names": {"LFO1 > ": "L1 "},          # optional on-screen name shortening
      "defines": {"HAS_LFO_BPM": 1},             # optional extra #defines in params.h
      "build": {"root": "..", "sources": ["src/maze_voice.c"], "cflags": ["-Isrc", "-DMAZE_VST=1"], "libs": ["-lm"]}
    }
The VST parameter index of each key is its position in chain_params; skins bind to it as "Parameter N".
Keep uid and so fixed across releases, and never reorder chain_params (saved projects store values by index).
"""
import json
import os
import shlex
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)


def load(path):
    cfg = json.load(open(path))
    for k in ("name", "vendor", "uid", "so", "module"):
        if k not in cfg:
            sys.exit("vst.json: missing %r" % k)
    if len(cfg["uid"]) != 4:
        sys.exit("vst.json: uid must be 4 characters (e.g. 'MzVc')")
    return cfg


def module_params(path):
    m = json.load(open(path))
    caps = m.get("capabilities", m)
    ps = caps.get("chain_params") or m.get("chain_params")
    if not ps:
        sys.exit("%s: no chain_params" % path)
    return ps


def c_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def fl(x):
    return repr(float(x)) + "f"


def short(name, table):
    for a, b in table.items():
        name = name.replace(a, b)
    return name


def gen_params(cfg, params, out):
    sn = cfg.get("short_names", {})
    lines = ["/* generated by mpc-vst-plugins tools/gen_vst.py from vst.json + module.json: do not edit */",
             "#pragma once",
             "typedef struct { const char *key, *name, *unit; float min, max, def; int nopts; "
             "const char *const *opts; int momentary; int string_display; } param_t;"]
    rows = []
    for i, p in enumerate(params):
        opts = p.get("options") or []
        name = c_str(short(p.get("name", p["key"]), sn))
        # "display":"string" -- the DSP's get_param() returns real text (a bank/patch name, a
        # status string), not a number to reformat. Without this, effGetParamDisplay's default
        # atof()-and-reformat path mangles any non-numeric string down to "0" (see docs/NOTES.md).
        is_str = int(p.get("display") == "string")
        if opts:
            lines.append("static const char *const OPTS_%d[] = {%s};" % (i, ", ".join(c_str(o) for o in opts)))
            d = p.get("default", 0)
            if isinstance(d, str):
                d = opts.index(d) if d in opts else 0
            norm = d / (len(opts) - 1) if len(opts) > 1 else 0
            rows.append("    {%s, %s, \"\", 0, 0, %s, %d, OPTS_%d, %d, %d}," % (
                c_str(p["key"]), name, fl(norm), len(opts), i, p.get("access") == "write", is_str))
        else:
            lo, hi = p.get("min", 0), p.get("max", 1)
            d = p.get("default", lo)
            norm = (d - lo) / (hi - lo) if hi > lo else 0
            rows.append("    {%s, %s, %s, %s, %s, %s, 0, 0, %d, %d}," % (
                c_str(p["key"]), name, c_str(p.get("unit", "")), fl(lo), fl(hi), fl(norm),
                p.get("access") == "write", is_str))
    lines += ["static const param_t PARAMS[] = {"] + rows + ["};", "#define NPARAMS %d" % len(params),
              "#define PLUG_NAME %s" % c_str(cfg["name"]), "#define PLUG_VENDOR %s" % c_str(cfg["vendor"]),
              "#define PLUG_UID 0x%08x /* '%s' */" % (int.from_bytes(cfg["uid"].encode(), "big"), cfg["uid"]),
              "#define PLUG_VERSION %d" % cfg.get("version", 1000)]
    lines += ["#define %s %s" % (k, v) for k, v in cfg.get("defines", {}).items()]
    open(out, "w").write("\n".join(lines) + "\n")


def entry(cfg):
    return ('<PLUGIN name="{n}" descriptiveName="{n}" format="VST" category="Synth" manufacturer="{v}" version="1.0" '
            'file="/sdcard/vst/{so}" uid="{u:x}" isInstrument="1" fileTime="0" infoUpdateTime="0" numInputs="0" '
            'numOutputs="2" isShell="0"/>').format(n=cfg["name"], v=cfg["vendor"], so=cfg["so"],
                                                  u=int.from_bytes(cfg["uid"].encode(), "big"))


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    path = os.path.abspath(sys.argv[1])
    here = os.path.dirname(path)
    cfg = load(path)
    build = os.path.join(here, "build")
    if sys.argv[2:] == ["--shell"]:
        b = cfg.get("build", {})
        root = os.path.normpath(os.path.join(here, b.get("root", ".")))
        for k, v in (("ROOT", root), ("PORT", os.path.relpath(here, root)), ("SO", cfg["so"]),
                     ("SOURCES", " ".join(b.get("sources", []))), ("CFLAGS", " ".join(b.get("cflags", []))),
                     ("LIBS", " ".join(b.get("libs", ["-lm"]))),
                     ("LAYOUT", "1" if cfg.get("layout") else "")):
            print("%s=%s" % (k, shlex.quote(v)))
        return
    params = module_params(os.path.join(here, cfg["module"]))
    os.makedirs(build, exist_ok=True)
    gen_params(cfg, params, os.path.join(build, "params.h"))
    print("params.h: %d params" % len(params))
    open(os.path.join(build, "pluginlist-entry.xml"), "w").write(entry(cfg) + "\n")

    import shadow_skin
    if cfg.get("layout"):
        layout = os.path.join(here, cfg["layout"])
    else:
        import studio
        ps, sections = studio.load_params(os.path.join(here, cfg["module"]))
        layout = os.path.join(build, "layout.auto.conf")
        open(layout, "w").write(studio.auto_layout(ps, sections))
        print("no layout in vst.json: auto-layout written to", layout)
    import shutil
    shutil.rmtree(os.path.join(build, "skin"), ignore_errors=True)   # no stale images from older builds
    art = os.environ.get("SHADOW_ART", os.path.join(build, "shadow_art"))
    print("skin:", shadow_skin.write_skin(os.path.join(build, "skin"), cfg["vendor"], cfg["name"], layout, params, art))


if __name__ == "__main__":
    main()
